### NumPy - Numerical Python
- deals with numerical data
- contains n-dimensional arrays

In [1]:
import numpy as np

In [2]:
! pip install numpy

In [3]:
numpy.array([1,2,3])

array([1, 2, 3])

In [ ]:
dir(np)

In [13]:
a = np.array([1,2,33,7])
print(a)
a

[ 1  2 33  7]


array([ 1,  2, 33,  7])

In [9]:
l = [9,6,7,5,3]
b = np.array(l)
type(b)

numpy.ndarray

#### numpy properties
- ndim 
     - no of dimensions of the array
- shape
     - returns the length of an array
- dtype
     - datatype of an element in an array
- size
     - returns the size of an array
- itemsize
     - returns the size of an element in bytes

In [18]:
a1 = np.array([2,4,6,8,10,"z"])
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.itemsize)
print(a1.dtype)
a1

1
(6,)
6
44
<U11


array(['2', '4', '6', '8', '10', 'z'], dtype='<U11')

In [39]:
a2 = np.array([[1,2,3],[4,5,6]])
#print(a2.ndim)
print(np.ndim(a2))
print(a2)


2
[[1 2 3]
 [4 5 6]]


In [24]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
sa = np.arange(15).reshape(3,5)
sa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
sa[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [35]:
r = np.random.randint(1,50,size = (3,3,3,3))
r

array([[[[19, 10, 14],
         [13, 26, 48],
         [29, 36,  5]],

        [[20, 47, 45],
         [16, 42, 32],
         [10, 38,  9]],

        [[48,  9, 12],
         [17, 21, 26],
         [46, 44, 22]]],


       [[[23, 12, 21],
         [37,  8,  5],
         [14, 45, 38]],

        [[41,  2, 21],
         [17, 37, 29],
         [24,  1, 28]],

        [[14,  8,  4],
         [39,  4, 31],
         [39, 45, 42]]],


       [[[17, 36, 41],
         [29, 35, 10],
         [24, 27, 29]],

        [[19, 22, 15],
         [16, 27,  9],
         [ 4, 38, 28]],

        [[17, 49,  1],
         [16, 10, 30],
         [49, 25, 20]]]])

In [37]:
ad = sa+1

In [38]:
ad

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [41]:
a = np.array([1,2,46,7,8,9])
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.exp(a))
print(np.log(a))

[1.         1.41421356 6.78232998 2.64575131 2.82842712 3.        ]
[0.84147098 0.90929743 0.90178835 0.6569866  0.98935825 0.41211849]
[ 0.54030231 -0.41614684 -0.43217794  0.75390225 -0.14550003 -0.91113026]
[2.71828183e+00 7.38905610e+00 9.49611942e+19 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[0.         0.69314718 3.8286414  1.94591015 2.07944154 2.19722458]


In [43]:
o = np.ones((3,3))
z = np.zeros((3,3))
print(o)
z

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
k = np.linspace(0,2,5) # creates an array evenly
k

array([0. , 0.5, 1. , 1.5, 2. ])

In [4]:
f = np.full((2,2),7) # creates a constant array
f

array([[7, 7],
       [7, 7]])

In [34]:
e = np.eye(2) # creates  a 2x2 array
e

array([[1., 0.],
       [0., 1.]])

In [7]:
r = np.random.random((2,2)) # creates an array with randpm values
r

array([[0.98440436, 0.8647252 ],
       [0.83842666, 0.82780886]])

In [8]:
em = np.empty((3,2))
em

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
s = np.array([1,2,3,5,6])
s[1]

2

In [9]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a[0][1]

2

In [15]:
a[1][2]

6

In [20]:
a[0:2,1]

array([2, 5])

In [23]:
a[0:1,2]

array([3])

In [26]:
a[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [27]:
a[a<3]

array([1, 2])

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a[[1,0,1,0],[0,1,2,0]] # (1,0)(0,1)(1,2)(0,0)

array([4, 2, 6, 1])

In [31]:
a1 = np.array([[1,4,5],[2,3,5]])
print(np.add(a,a1))
print(np.subtract(a,a1))
print(np.multiply(a,a1))
print(np.divide(a,a1))

[[ 2  6  8]
 [ 6  8 11]]
[[ 0 -2 -2]
 [ 2  2  1]]
[[ 1  8 15]
 [ 8 15 30]]
[[1.         0.5        0.6       ]
 [2.         1.66666667 1.2       ]]


In [35]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [39]:
np.info(np.ndarray.size)

Number of elements in the array.

Equal to ``np.prod(a.shape)``, i.e., the product of the array's
dimensions.

Notes
-----
`a.size` returns a standard arbitrary precision Python integer. This 
may not be the case with other methods of obtaining the same value
(like the suggested ``np.prod(a.shape)``, which returns an instance
of ``np.int_``), and may be relevant if the value is used further in
calculations that may overflow a fixed size integer type.

Examples
--------
>>> x = np.zeros((3, 5, 2), dtype=np.complex128)
>>> x.size
30
>>> np.prod(x.shape)
30


In [41]:
a1.dtype

dtype('int32')

In [42]:
a1.astype(float)

array([[1., 4., 5.],
       [2., 3., 5.]])

In [43]:
h = a1.view()

In [44]:
h

array([[1, 4, 5],
       [2, 3, 5]])

In [47]:
t = np.save('my_array',a)
t

In [53]:
t1 = np.load('my_array.npy')

In [54]:
t1

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a.sum()
a.min()
a.max()
a.mean()
np.median(a)

3.5

In [58]:
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

In [59]:
np.std(a)

1.707825127659933

In [60]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [61]:
a1

array([[1, 4, 5],
       [2, 3, 5]])

In [65]:
s = np.sort(a1)

In [66]:
s

array([[1, 4, 5],
       [2, 3, 5]])

In [73]:
np.sort(a1,axis=0) # 0-col, 1-row

array([[1, 3, 5],
       [2, 4, 5]])

In [74]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [78]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [81]:
a.reshape(3,-2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [83]:
np.append(a,a1)

array([1, 2, 3, 4, 5, 6, 1, 4, 5, 2, 3, 5])

In [84]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.insert(a,1,5)

array([1, 5, 2, 3, 4, 5, 6])

In [86]:
np.delete(a,1)

array([1, 3, 4, 5, 6])

In [87]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
a1

array([[1, 4, 5],
       [2, 3, 5]])

In [90]:
np.vstack((a,a1)) # stacks vertically (row-wise)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 5],
       [2, 3, 5]])

In [91]:
np.hstack((a,a1)) # stacks horizontally(column-wise)

array([[1, 2, 3, 1, 4, 5],
       [4, 5, 6, 2, 3, 5]])

In [92]:
np.r_[a,a1] #stacks row-wise

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 5],
       [2, 3, 5]])

In [93]:
np.c_[a,a1] # stacks column-wise

array([[1, 2, 3, 1, 4, 5],
       [4, 5, 6, 2, 3, 5]])

In [95]:
np.column_stack((a,a1))

array([[1, 2, 3, 1, 4, 5],
       [4, 5, 6, 2, 3, 5]])

In [97]:
np.row_stack((a,a1))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 5],
       [2, 3, 5]])

In [98]:
# r_ ,row_stack,vstack - stacks row-wise
# c_,column_stack,hstack - stacks column-wise

In [100]:
np.vsplit(a,2) # splits row-wise

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [101]:
np.hsplit(a1,3)

[array([[1],
        [2]]), array([[4],
        [3]]), array([[5],
        [5]])]

In [106]:
g = np.array([1,2,3])
j= np.arange(10,25,5)
j

array([10, 15, 20])

In [111]:
np.concatenate((g,j))

array([ 1,  2,  3, 10, 15, 20])