# Maps
- it produces a list of results that it apply given function to each 
  item of a given iterable(list,tuple,sets etc...)
- syntax : map(function,iterable)

In [1]:
def addition(n):
    return n+n
# 1+1=2,2+2=4,3+3=6,4+4=8,5+5=10
result=list(map(addition,range(1,6)))
print(result)

[2, 4, 6, 8, 10]


In [6]:
# Function to print a squares of numbers in given range b/w 1 to 6
def suares(n):
    return n**2
result=tuple(map(suares,range(1,6)))
print(result)

(1, 4, 9, 16, 25)


In [7]:
def suares(n): # n=1,2,3,4
    return n*n # 1,4,9,16
result=set(map(suares,range(1,5)))
print(result)

{16, 1, 4, 9}


# filters
- filters function in python is used to check whether given element is boolean or not(T or F).
- This method filters given iterable, test each element is True or False, and returns the element which is True.
- syntax : f:x -->{T,F}

In [10]:
lst = [1,2,'a','b',3,'c']
def digit(c):
    c=str(c)
    if c.isdigit():
        return True
    return False
digit('a')
list(filter(digit,lst))

[1, 2, 3]

In [9]:
print(dir(str),end=" ")

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill'] 

In [16]:
def prime(n):
    if n<2:
        return False
    for i in range(2,n//2+1):
        if n%i==0:
            return False
    return True
lb,ub=100,200
primelist=list(filter(prime,range(lb,ub)))
print(primelist)

[101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199]


In [11]:
2//2

1

In [12]:
4//2

2

In [13]:
4/2

2.0

In [14]:
4%2

0

In [15]:
5%2

1

# Lambdas
- lambda is just a function without a name or anonymous function.
- syntax : lambda argument : expression
- lambda x : x^3
- lambda takes 0 or more arguments but only one expression.

In [17]:
result =lambda x:x**3
result(4)

64

In [20]:
list(map(lambda x:x**3,[1,2,3,4,5]))

[1, 8, 27, 64, 125]

In [21]:
even = lambda x:x%2==0
result=list(filter(even,range(10,20)))
print(result)

[10, 12, 14, 16, 18]


In [22]:
from random import randint
def generateMarks(n, lb, ub):
    filename = 'DataFiles/marks.txt'
    with open(filename, 'w') as f:
        for i in range(n):
            marks = randint(lb,ub)
            f.write(str(marks)+'\n')
    return
generateMarks(10000, 0, 100)

In [23]:
# class average
def readMarkslist(filepath):
    with open(filepath, 'r') as f:
        filedata = f.read().split()
    return list(map(int, filedata))

def classAverage(filepath):
    markslist = readMarkslist(filepath)
    return sum(markslist)//len(markslist)

filepath = 'DataFiles/marks.txt'
classAverage(filepath)

50

# Python Libraries for Data Science
- Numpy
- Pandas
- Matplotlib

# Numpy
- Numerical python is base N-dimensional array package.
- It is python library
- it is used to create multidimensional arrays for fast operations.


In [25]:
# create 1D array
import numpy as np
array_1d = np.array([2,4,5,6,7,8])
print(array_1d)

[2 4 5 6 7 8]


In [26]:
# create 2D array
import numpy as np
array_2d = np.array([[2,4,5],[6,7,8]])
print(array_2d)

[[2 4 5]
 [6 7 8]]


In [28]:
import numpy as np
li = [1,2,3,'sudha']
array_1d = np.array(li)
print(array_1d)

['1' '2' '3' 'sudha']


In [29]:
import numpy as np
li = [[1,'sudha'],['sana',7895]]
array_2d = np.array(li)
print(array_2d)

[['1' 'sudha']
 ['sana' '7895']]


In [30]:
import numpy as np
li = [[1,'sudha'],['sana',7895],['sdc','ap']]
array_3d = np.array(li)
print(array_3d)

[['1' 'sudha']
 ['sana' '7895']
 ['sdc' 'ap']]


In [31]:
import numpy as np
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [40]:
# reverse the array
a[::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [41]:
a = [1,2]
a[::-1]

[2, 1]

In [43]:
import numpy as np
x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
z = [[1,2],[3,4],[5,6]]
x = np.array(z)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
y = x+10
y

array([[11, 12],
       [13, 14],
       [15, 16]])

In [54]:
a = [1,2,3]
x = np.array(a)
#print(x)
print(np.sqrt(x))
print(np.sin(x))
print(np.cos(x))
print(np.log(x))

[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]
