## Numpy
* Numpy : Numerical python
    * **Advantages:**
        * convenience and speed 
            * Numpy is much faster than the standard python ways to do computations
            * Can write vectorised code on numpy arrays, not on lists
            * which is convenient to read and write
            * It takes Less memory as compared to python lists 
            * Can handle the vast amount of data 

    a. Used for scientific computing and data analysis
    b. Written as ndarray (n-dimensional , homogeneous) or array
        * Commonly integers or floats
    c. Creating Numpy Arrays:
        * 1D, 2D, 3D array
        * Convert lists, tuple to np.arrays

    d. Initialize Array:

        * np.ones(shape,dtype)
        * np.zeros(shape,dtype)
        * np.random.random(shape)
        * np.arange(start,end,step)
        * np.linspace(start,end,length of array)
        * np.full(shape,value)
        * np.tile(array,number of repetitions) or (array,shape)
        * np.eye(value,dtype) - identical matrix
        * np.random.randint(start,end,shape)
        * np.nonzero(array)
        * max,min,median,mode
        * array Transpose
        * np.vstack(array)
        * np.hstack(array
        * argsort,argmin,argmax,np.log10,pi
        
    e. Inspect the structure and content of array

        * np.shape(array)
        * np.dtype()
        * np.ndim()
        * np.itemsize()
        * np.reshape(factors of size of array)

In [2]:
import numpy as np
arr = np.array([(1,2,3,4),(4,5,6,7),(1,8,6,9)])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 8, 6, 9]])

In [28]:
arr.shape

(3, 4)

In [29]:
arr.ndim

2

In [32]:
arr.reshape((6,2))

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7],
       [1, 8],
       [6, 9]])

In [5]:
# np.ones(shape,dtype)
arr1 = np.ones((3,3),dtype= str)
arr1

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [8]:
# np.zeros(shape,dtype)
arr2 = np.zeros((3,3),dtype = int)
arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
arr3 = np.random.random((3,4))  # 0-1 
arr3

array([[0.81894335, 0.96958578, 0.52505718, 0.63603024],
       [0.33320556, 0.67754268, 0.18139482, 0.19204177],
       [0.71133739, 0.32029659, 0.08009751, 0.06829418]])

In [14]:
arr4 = np.arange(2,10,2)
arr4

array([2, 4, 6, 8])

In [21]:
arr5 = np.linspace(1,5,5)
arr5

array([1., 2., 3., 4., 5.])

In [23]:
arr6 = np.eye(5)  # identical matrix
arr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr7 = np.full((5,6),"u")
arr7

array([['u', 'u', 'u', 'u', 'u', 'u'],
       ['u', 'u', 'u', 'u', 'u', 'u'],
       ['u', 'u', 'u', 'u', 'u', 'u'],
       ['u', 'u', 'u', 'u', 'u', 'u'],
       ['u', 'u', 'u', 'u', 'u', 'u']], dtype='<U1')

In [26]:
arr8 = np.nonzero([1,2,0,5,0,7,5]) # it returns nonzero elements indices
arr8

(array([0, 1, 3, 5, 6], dtype=int64),)

In [27]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [33]:
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs

# Pandas
* Which is a build in Library and using Pandas heavily for data manipulation, visualisation, building machine learning models, etc.
* There are two main data structures in Pandas - Series and Dataframes

### The pandas Series (similar to a numpy array)

* A dataframe is simply a table where each column is a pandas series. 
    * Creating a pandas series
    * Indexing series
    
### Dataframes

* Dataframe is the most widely used data-structure in data analysis. It is a table with rows and columns, with rows having       an index and columns having meaningful names.

    * Creating dataframes from dictionaries
    * Importing CSV data files as pandas dataframes
    * Reading and summarising dataframes
    * Sorting dataframes
    

    
[Birds_dataset](https://drive.google.com/file/d/1A5Z-uNxmKLljstrX8j-1j2ydThYbe6JU/view?usp=sharing)

### Creating Pandas Series
* A dataframe is simply a table where each column is a pandas series.

In [34]:
import pandas as pd

In [38]:
# creating pandas series from a list
s1 = pd.Series([1,2,3,4,5,6,7]) # series index starts from 0
print(type(s1))
s1

<class 'pandas.core.series.Series'>


0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [39]:
s1 = pd.Series([1,2,"lavanya",4.8989,5,6,7]) # series index starts from 0
print(type(s1))
s1

<class 'pandas.core.series.Series'>


0          1
1          2
2    lavanya
3     4.8989
4          5
5          6
6          7
dtype: object

## Indexing of pandas series

In [43]:
s1[1]
s1[6]
s1[2]

'lavanya'

In [46]:
s1[2:5]
s1[1:6]
s1[1:6:2] # strat

1         2
3    4.8989
5         6
dtype: object

## Pandas Dataframe
* Dataframe is the most widely used data-structure in data analysis. It is a table with rows and columns, with rows having an index and columns having meaningful names.

* Creating dataframes from dictionaries

* There are various ways of creating dataframes, such as creating them from dictionaries, JSON objects, reading from txt, CSV     files, etc.

*One of the main purposes of pandas is to deal with tabular data, i.e. data that comes from tables or spreadsheets.*

In [3]:
# creating DF using dict
import pandas as pd
di = {   "name": ["chandu",'shaik',"keerthi","srikanthi"],
         "age" : [12,34,22,34]
     }
df = pd.DataFrame(di)
df

name  age
0     chandu   12
1      shaik   34
2    keerthi   22
3  srikanthi   34

In [4]:
import pandas as pd
di = {   "name": pd.Series(["chandu",'shaik',"keerthi","srikanthi"],index = ['a','b','c','d']),
         "age" : pd.Series([12,34,22,34],index = ['a','b','c','d'])
     }
df = pd.DataFrame(di)
df

name  age
a     chandu   12
b      shaik   34
c    keerthi   22
d  srikanthi   34

In [23]:
di.keys()

dict_keys(['name', 'age'])

In [26]:
print(di.values())

dict_values([a       chandu
b        shaik
c      keerthi
d    srikanthi
dtype: object, a    12
b    34
c    22
d    34
dtype: int64])


In [24]:
di.items()

dict_items([('name', a       chandu
b        shaik
c      keerthi
d    srikanthi
dtype: object), ('age', a    12
b    34
c    22
d    34
dtype: int64)])

```NOTE``` : **Number of elements in index list is always equal to the number of elements in specified data list**

In [12]:
di1 = {   "name": pd.Series(["chandu",'shaik',"keerthi","srikanthi"],index = ['a','b','c','d']),
          "age" : pd.Series([12,34,22],index = ['a','b','c'])
     }
df1 = pd.DataFrame(di1)
df1    # NaN -- Not a Number

name   age
a     chandu  12.0
b      shaik  34.0
c    keerthi  22.0
d  srikanthi   NaN

In [10]:
di1 = {   "name": pd.Series(["chandu",'shaik',"keerthi","srikanthi"],index = ['a','b','c','d']),
          "age" : pd.Series([12,34,22])
     }
df1 = pd.DataFrame(di1)
df1    # NaN -- Not a Number

name   age
a     chandu   NaN
b      shaik   NaN
c    keerthi   NaN
d  srikanthi   NaN
0        NaN  12.0
1        NaN  34.0
2        NaN  22.0

In [13]:
di1 = {   "name": pd.Series(["chandu",'shaik',"keerthi","srikanthi"]),
          "age" : pd.Series([12,34,22])
     }
df1 = pd.DataFrame(di1)
df1    # NaN -- Not a Number

name   age
0     chandu  12.0
1      shaik  34.0
2    keerthi  22.0
3  srikanthi   NaN

In [14]:
df1.index = ['a','b','c','d']
df1

name   age
a     chandu  12.0
b      shaik  34.0
c    keerthi  22.0
d  srikanthi   NaN

In [16]:
# shape (1000,200)
df1.isnull().sum()

name    0
age     1
dtype: int64

In [18]:
df1.notnull().sum()

name    4
age     3
dtype: int64

In [19]:
df1.shape  # (rows,columns)

(4, 2)

In [20]:
df1.columns

Index(['name', 'age'], dtype='object')

In [21]:
df1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [22]:
df1.values

array([['chandu', 12.0],
       ['shaik', 34.0],
       ['keerthi', 22.0],
       ['srikanthi', nan]], dtype=object)

In [70]:
# Reading csv file in dataframe 
data = pd.read_csv("datasets_bird.csv")
data

id    huml   humw   ulnal  ulnaw   feml  femw    tibl  tibw   tarl  \
0      0   80.78   6.68   72.01   4.88  41.81  3.70    5.50  4.03  38.70   
1      1   88.91   6.63   80.53   5.59  47.04  4.30   80.22  4.51  41.50   
2      2   79.97   6.37   69.26   5.28  43.07  3.90   75.35  4.04  38.31   
3      3   77.65   5.70   65.76   4.77  40.04  3.52   69.17  3.40  35.78   
4      4   62.80   4.84   52.09   3.73  33.95  2.72   56.27  2.96  31.88   
5      5   61.92   4.78   50.46   3.47  49.52  4.41   56.95  2.73  29.07   
6      6   79.73   5.94   67.39   4.50  42.07  3.41   71.26  3.56  37.22   
7      7   86.98   5.68   74.52   4.55  44.46  3.78   76.02  3.81  37.94   
8      8  118.20   7.82  116.64   6.13  59.33  5.45  110.00  5.58  61.62   
9      9  145.00  10.42  144.00   7.05  70.96  7.44  120.00  7.31  78.67   
10    10  165.00  11.45  156.00   8.68  80.25  7.85  143.00  8.25  86.61   
11    11  186.00   9.83  152.00   8.76  56.02  7.02  185.00  8.07  90.80   
12    12  172.00   8.44  142.00   8.43  52.18  6.68  180.00  9.62  82.58   
13    13  148.91   6.78  121.35   6.50  44.29  6.33  155.00  6.68  73.71   
14    14  149.19   6.98  121.48   6.21  43.33  5.39  155.00  6.61  75.65   
15    15  140.59   6.59  115.97   5.81  39.75  5.61  166.00  7.83  74.86   
16    16  135.23   6.22  108.78   5.83  37.99  5.13  157.00  7.18  72.44   
17    17  124.53   6.01  100.37   5.82  34.54  5.43  145.00  7.12  65.92   
18    18  127.03   6.18  102.53   5.64  36.52  4.89  150.00  6.78  67.27   
19    19  106.02   4.47   95.79   4.33  41.96  4.80  129.59  6.94  70.29   
20    20  113.84   4.80  100.71   4.39  43.95  5.08  133.27  7.41  70.91   
21    21  108.62   5.04   97.70   4.66  45.08  5.78  128.00  7.14  65.48   
22    22  110.33   5.86   97.10   4.60  43.82  5.73  126.00  7.86  64.17   
23    23   63.62   3.42   59.00   2.75  30.16  2.92   74.66  4.38  39.26   
24    24   70.73   3.69   65.19   2.93  32.52  3.54   80.42  4.36  43.70   
25    25   71.65   3.37   66.11   2.77  36.98  3.06   77.11  3.94  38.04   
26    26   47.51   7.23   32.49   8.26  50.29  5.00   75.20  4.95  22.51   
27    27   46.20   7.06   32.73   8.58  52.15  5.11   75.99  4.77  23.24   
28    28   41.13   6.71   31.00   7.73  49.51  4.69   71.94  4.54  22.46   
29    29   72.50  14.78   45.83  10.33  77.02  7.76  128.75  6.49  32.48   
..   ...     ...    ...     ...    ...    ...   ...     ...   ...    ...   
390  390   20.43   1.59   22.68   1.39  20.00  1.54   35.63  1.33  25.57   
391  391   22.19   1.86   24.93   1.52  24.14  1.78   40.17  1.73  29.61   
392  392   23.27   2.00   24.80   1.83  26.04  1.79   41.91  1.67  29.76   
393  393   18.97   1.58   21.26   1.40  21.50  1.55   36.52  1.52  25.04   
394  394   15.99   1.35   18.32   1.13  15.84  1.19   30.05  1.23  22.94   
395  395   15.62   1.28   18.52   1.06  15.75  1.17   28.63  1.03  21.39   
396  396   16.51   1.47   20.56   1.43  15.88  1.27     NaN  1.19  17.63   
397  397   16.80   1.58   19.77   1.39  16.86  1.29   29.75  1.18  21.77   
398  398   15.55   1.48   18.93   1.30  17.58  1.23   31.65  1.14  24.12   
399  399   23.32   2.06   27.90   1.84  22.49  1.66   34.77  1.42  23.05   
400  400   20.41   1.82   22.66   1.71  18.14  1.52   29.30  1.21  20.29   
401  401   21.53   1.91   25.30   1.67  20.80  1.65   34.08  1.33  23.86   
402  402   22.84   2.21   27.70   2.06  22.13  1.72   34.60  1.69  25.08   
403  403   20.95   1.89   24.12   1.66  21.24  1.84   36.71  1.53  25.99   
404  404   20.36   1.87   22.19   1.60    NaN  1.77   37.47  1.64  25.54   
405  405   17.30   1.68   20.43   1.33  15.51  1.15   25.96  0.88  17.41   
406  406   16.86   1.58   20.72   1.36  14.92  1.13   24.56  0.98  16.76   
407  407   15.70   1.42   18.58   1.20  15.22  1.08   25.39  0.92  16.88   
408  408   19.54   1.86   23.35   1.47  18.34  1.46   29.05  1.35  19.68   
409  409   23.27   2.15   27.62   2.16  21.86  1.64   35.55  1.51  23.23   
410  410   23.04   2.15   28.29   1.94  21.46  1.67   

In [28]:
data.shape

(420, 12)

In [29]:
data.ndim

2

In [31]:
data.isnull().sum()

id       0
huml     1
humw     1
ulnal    3
ulnaw    2
feml     2
femw     1
tibl     2
tibw     1
tarl     1
tarw     1
type     0
dtype: int64

In [32]:
data.notnull().sum()

id       420
huml     419
humw     419
ulnal    417
ulnaw    418
feml     418
femw     419
tibl     418
tibw     419
tarl     419
tarw     419
type     420
dtype: int64

In [34]:
data.head(3) # top 3 rows

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
0   0  80.78  6.68  72.01   4.88  41.81   3.7   5.50  4.03  38.70  3.84   SW
1   1  88.91  6.63  80.53   5.59  47.04   4.3  80.22  4.51  41.50  4.01   SW
2   2  79.97  6.37  69.26   5.28  43.07   3.9  75.35  4.04  38.31  3.34   SW

In [36]:
data.tail(4)  # it returns last 4 rows

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw  \
416  416  19.21  1.64  20.76   1.49  19.24  1.45  33.21  1.28  23.60  1.15   
417  417  18.79  1.63  19.83   1.53  20.96  1.43  34.45  1.41  22.86  1.21   
418  418  20.38  1.78  22.53   1.50  21.35  1.48  36.09  1.53  25.98  1.24   
419  419  17.89  1.44  19.26   1.10  17.62  1.34  29.81  1.24  21.69  1.05   

    type  
416   SO  
417   SO  
418   SO  
419   SO

In [40]:
data.sample(4) # selected rows randomly --  4 rows

id    huml  humw   ulnal  ulnaw   feml  femw    tibl  tibw   tarl  tarw  \
300  300   38.66  3.83   43.71   3.02  40.05  3.51   64.97  2.95  47.69  2.57   
126  126   34.17  2.21   27.80   1.97  35.82  2.32   51.77  2.06  33.13  1.93   
384  384   48.20  4.08   61.94   3.75  40.11  3.10   62.09  3.21  37.26  2.46   
224  224  120.00  8.38  130.00   6.41  89.93  8.46  116.17  7.52  84.18  6.97   

    type  
300   SO  
126    W  
384   SO  
224    R

In [43]:
len(data.columns)
data.columns

Index(['id', 'huml', 'humw', 'ulnal', 'ulnaw', 'feml', 'femw', 'tibl', 'tibw',
       'tarl', 'tarw', 'type'],
      dtype='object')

In [44]:
data.index

RangeIndex(start=0, stop=420, step=1)

In [55]:
data.set_index("huml",inplace= True)
# data = data.set_index("huml")

In [56]:
data.head()

id  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
huml                                                                     
80.78   0  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
88.91   1  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
79.97   2  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
77.65   3  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
62.80   4  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW

## Sorting data 
    * sort by columns
    * sort by rows
    * axis = 1 -- columns and axis = 0 -- rows

In [59]:
data.head()

id  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
huml                                                                     
80.78   0  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
88.91   1  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
79.97   2  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
77.65   3  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
62.80   4  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW

In [60]:
data.sort_index(axis = 1,ascending = False).head()

ulnaw  ulnal type  tibw   tibl  tarw   tarl  id  humw  femw   feml
huml                                                                     
80.78   4.88  72.01   SW  4.03   5.50  3.84  38.70   0  6.68  3.70  41.81
88.91   5.59  80.53   SW  4.51  80.22  4.01  41.50   1  6.63  4.30  47.04
79.97   5.28  69.26   SW  4.04  75.35  3.34  38.31   2  6.37  3.90  43.07
77.65   4.77  65.76   SW  3.40  69.17  3.41  35.78   3  5.70  3.52  40.04
62.80   3.73  52.09   SW  2.96  56.27  3.13  31.88   4  4.84  2.72  33.95

In [73]:
data.sort_index(axis=0,ascending=True).head()

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
0   0  80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
1   1  88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
2   2  79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
3   3  77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
4   4  62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW

In [61]:
data.columns

Index(['id', 'humw', 'ulnal', 'ulnaw', 'feml', 'femw', 'tibl', 'tibw', 'tarl',
       'tarw', 'type'],
      dtype='object')

In [64]:
type(data["type"]) # get type columns -- returns series object

pandas.core.series.Series

In [65]:
type(data[["type"]])  # -- returns DF object 

pandas.core.frame.DataFrame

In [66]:
data[["type",'ulnaw']]

type  ulnaw
huml              
80.78    SW   4.88
88.91    SW   5.59
79.97    SW   5.28
77.65    SW   4.77
62.80    SW   3.73
61.92    SW   3.47
79.73    SW   4.50
86.98    SW   4.55
118.20   SW   6.13
145.00   SW   7.05
165.00   SW   8.68
186.00   SW   8.76
172.00   SW   8.43
148.91   SW   6.50
149.19   SW   6.21
140.59   SW   5.81
135.23   SW   5.83
124.53   SW   5.82
127.03   SW   5.64
106.02   SW   4.33
113.84   SW   4.39
108.62   SW   4.66
110.33   SW   4.60
63.62    SW   2.75
70.73    SW   2.93
71.65    SW   2.77
47.51    SW   8.26
46.20    SW   8.58
41.13    SW   7.73
72.50    SW  10.33
...     ...    ...
20.43    SO   1.39
22.19    SO   1.52
23.27    SO   1.83
18.97    SO   1.40
15.99    SO   1.13
15.62    SO   1.06
16.51    SO   1.43
16.80    SO   1.39
15.55    SO   1.30
23.32    SO   1.84
20.41    SO   1.71
21.53    SO   1.67
22.84    SO   2.06
20.95    SO   1.66
20.36    SO   1.60
17.30    SO   1.33
16.86    SO   1.36
15.70    SO   1.20
19.54    SO   1.47
23.27    SO   2.16
23.04    SO   1.94
21.21    SO   1.62
21.92    SO   1.49
12.95    SO   1.03
13.63    SO   1.06
17.96    SO   1.33
19.21    SO   1.49
18.79    SO   1.53
20.38    SO   1.50
17.89    SO   1.10

[420 rows x 2 columns]

### Indexing and Selecting Data
    In this section, you will:

    Select rows from a dataframe
    Select columns from a dataframe
    Select subsets of dataframes


In [67]:
data.head()

id  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
huml                                                                     
80.78   0  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
88.91   1  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
79.97   2  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
77.65   3  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
62.80   4  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW

In [71]:
data[5:10:2]

id    huml   humw   ulnal  ulnaw   feml  femw    tibl  tibw   tarl  tarw  \
5   5   61.92   4.78   50.46   3.47  49.52  4.41   56.95  2.73  29.07  2.83   
7   7   86.98   5.68   74.52   4.55  44.46  3.78   76.02  3.81  37.94  3.81   
9   9  145.00  10.42  144.00   7.05  70.96  7.44  120.00  7.31  78.67  6.34   

  type  
5   SW  
7   SW  
9   SW

In [75]:
data["type"].value_counts()

SO    128
SW    116
W      65
R      50
P      38
T      23
Name: type, dtype: int64

In [78]:
print(data["humw"].min())
print(data["humw"].max())

1.14
17.84


## concat data
## Export data

In [ ]:
Q : if None :
        print(True)
        
        
        
1. true
2. True
3. None
4. False